version: '2.4'
services:
  docs:
    build:
      context: .
    environment:
      # - PY_REPO=https://github.com/datajoint/datajoint-python.git
      # - PY_BRANCH=master
      - PY_REPO=https://github.com/guzman-raphael/datajoint-python.git
      - PY_BRANCH=master
      # - PY_BRANCH=v0.12.dev4
      # - M_REPO=https://github.com/datajoint/datajoint-matlab.git
      # - M_BRANCH=master
      - M_REPO=https://github.com/guzman-raphael/datajoint-matlab.git
      - M_BRANCH=docs-virt-module
      - DOCS_REPO=https://github.com/datajoint/datajoint-docs.git
    working_dir: /src
    user: 1000:1000
    command: TEST
    # command: PROD
    volumes:
      - .:/src/datajoint-docs
    ports:
      - "8080:8000"